# Generated by Django 4.1.7 on 2023-03-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("kitchen", "0004_delete_ingredient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("unit", models.CharField(default="g", max_length=63)),
                (
                    "dishes",
                    models.ManyToManyField(
                        related_name="ingredients", to="kitchen.dish"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
