# Generated by Django 4.1.7 on 2023-03-28 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("storehouse", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="dishes",
        ),
    ]
