# Generated by Django 4.1.7 on 2023-03-29 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("storehouse", "0002_remove_ingredient_dishes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="unit",
        ),
    ]
