# Generated by Django 4.1.7 on 2023-03-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storehouse", "0003_remove_ingredient_quantity_remove_ingredient_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
