# Generated by Django 4.1.7 on 2023-03-28 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0003_alter_dish_options_ingredient_quantity_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ingredient",
        ),
    ]
