# Generated by Django 4.1.7 on 2023-03-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storehouse", "0002_remove_ingredient_dishes"),
        ("kitchen", "0004_delete_ingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="ingredients",
            field=models.ManyToManyField(
                default=None, related_name="dishes", to="storehouse.ingredient"
            ),
        ),
    ]
